language: go

jobs:
  include:
    - os: linux
      go: "1.13.x"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "1.13.x"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod

    - os: windows
      go: "1.13.x"
      cache:
        directories:
          - $USERPROFILE/AppData/Local/go-build
          - $USERPROFILE/gopath/pkg/mod

env:
  - GO111MODULE=on

install:
  - go version
  - go env
  - go get -t -d -v ./...

script:
  - go build ./...
  - |
    if [[ "${GITHUB_TOKEN}" != "" ]]; then
      go test -v -race -coverprofile=coverage.txt . ./update
    else
      go test -v -race -short . ./update
    fi

after_success:
  - if [ -f coverage.txt ]; then bash <(curl -s https://codecov.io/bash); fi
